[package]
name = "soldeer"
version = "0.1.5"
edition = "2021"
authors = ["m4rio"]
license = "MIT"
description = "A solidity package manager written in rust. It's minimal and easy within your solidity project. Works best with foundry."
repository = "https://github.com/mario-eth/soldeer"
homepage = "https://github.com/mario-eth/soldeer"
readme = "./README.md"
keywords = ["solidity", "package-manager"]
categories = ["development-tools", "package-management"]
exclude = ["crawler/*", ".github/*", ".vscode/*"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.1"
toml = "0.7.6"
serde = "1.0.171"
serde_derive = "1.0.171"
tokio = "1.29.1"
tokio-dl-stream-to-disk = "1.0.0"
zip-extract = "0.1.2"
reqwest = "0.11.18"
toml_edit = "0.9.1"
lazy_static = "1.4.0"
clap = { version = "4.4.8", features = ["derive"] }
serial_test = "2.0.0"
sha256 = "1.4.0"

[dev-dependencies]
tokio-test = "*"
