[package]
authors = ["m4rio"]
categories = ["development-tools", "package-management"]
description = "A solidity package manager written in rust. It's minimal and easy within your solidity project. Works best with foundry."
edition = "2021"
exclude = [".github/*", ".vscode/*"]
homepage = "https://github.com/mario-eth/soldeer"
keywords = ["solidity", "package-manager"]
license = "MIT"
name = "soldeer"
readme = "./README.md"
repository = "https://github.com/mario-eth/soldeer"
version = "0.2.9"

[dependencies]
chrono = {version = "0.4.37", features = ["serde"]}
clap = {version = "4.5.4", features = ["derive"]}
email-address-parser = "2.0.0"
regex = "1.10.4"
reqwest = {version = "0.12.3", features = ["blocking", "json", "multipart"]}
rpassword = "7.3.1"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.115"
serial_test = "3.0.0"
sha256 = "1.5.0"
simple-home-dir = "0.3.2"
tokio = "1.37.0"
tokio-dl-stream-to-disk = "1.0.1"
toml = "0.8.12"
toml_edit = "0.22.9"
uuid = {version = "1.8.0", features = ["serde", "v4"]}
walkdir = "2.5.0"
yansi = "1.0.1"
zip = "0.6.6"
zip-extract = "0.1.3"

[dev-dependencies]
tokio-test = "0.4.4"

[lib]
name = "soldeer"
path = "src/lib.rs"

[[bin]]
name = "soldeer"
path = "src/main.rs"
