
# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
libs = ["dependencies"]
script = "script"
solc = "0.8.20"
src = "src"
test = "test"

[dependencies]
forge-std = "1.8.2"
