name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pre-requirements Nightly
      run: rustup toolchain install nightly
    - name: Pre-requirements Nightly x86_64-unknown-linux-gnu
      run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Format
      run: cargo +nightly fmt --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
